### PR TITLE
Custom pagination

### PR DESCRIPTION
**Pull request by henryrowswell**
SOLUTION 1:

Reorganized files so that pagination within each section works naturally. To navigate from the end of one section to the beginning of the next section (such as from Resources -> About), I added a custom pagination override to `post_pagination.html`. This way, any page can override its normal ordering and link the "prev" or "next" buttons directly to any other page.

This is one of two solutions I came up with to solve the pagination problem. See [here](https://github.com/henryrowswell/community-hub/pull/1) for the other solution, which doesn't involve any custom pagination logic. However, I personally think this might be the better solution, as it allows for a flatter file structure and provides options in the future for additional customization.

File structure looks like this now:
```
/docs
    /00-docs-root
        00-docs-root.md
    /01-wellbeing
        00-wellbeing-pyramid.md
        01-wellbeing-harms.md
        02-wellbeing-health.md
        03-wellbeing-social.md
        04-wellbeing-children-teens.md
        05-wellbeing-mindfulness.md
    /02-freedom
        00-freedom-pyramid.md
        01-freedom-harms.md
        02-freedom-openness.md
        03-freedom-diversity.md
        04-freedom-security.md
        05-freedom-privacy.md
    /03-society
        00-society-pyramid.md
        01-society-harms.md
        02-society-inclusion.md
        03-society-regulation.md
        04-sustainable-business.md
        05-society-digital-rights.md
    /04-alignment
        00-alignment-pyramid.md
        01-alignment-humane-design.md
        02-alignment-ethics.md
        03-alignment-best-practices.md
        04-alignment-standards.md
/activities
    00-activities-root.md
/resources
    00-resources-root.md
/about
    00-about-root.md
    01-about-join.md
    02-about-faq.md
    03-about-code-of-conduct.md
    04-about-privacy-policy.md

/_pages
    404.md
    focus-05-harms-of-technology.md
    terms.md
    blog.md
```

### CODE REVIEW

**Comment by henryrowswell** [comment]
Also, I should note that the I wasn't sure where `/focus/harms-of-technology/` fit into all this, so I moved it to `_pages` for now.

**Comment by aschrijver** [comment]
Your solution 1) is great. I like the extension you made to the navigation mechanism. It is intuitive enough.

> Also, I should note that the I wasn't sure where `/focus/harms-of-technology/` fit into all this, so I moved it to `_pages` for now.

In HTC - after reorganization - we specifically address the Harms of Technology separately, i.e. we separate harms from solutions. Separating the negativity from optimism, positivity, solution-focus.

On the webstie landing page there is a link to 'Harms of Technology' that leads to a page that only has the 3 Harms categories in the sidebar, but if you go to the Docs section there - below each pyramid - the corresponding Harms page is also included.

**Comment by aschrijver** [comment]
This is a big improvement! Thanks so much!

**Comment by aschrijver** [comment]
I had to make this fix, as the `_config.yml` was setting Blog-style permalinks as the default, and it made the `main.css` unfindable. I moved that permalink definition to the `posts` section. I also removed the docs navigation there (wasn't rendered anyway).

I also made 'wide' pages the default for the site. Don't know if that is smart, as 'small' is no longer an option then, but the information density of this theme is really low, so wide pages are generally preferable.

**Pull request merged**
